extends RefCounted
## The cave's layout. GENERATED by tools/gen_cave.py - edit that and re-run it.

const CHUNKS := ["res://levels/cave/mesh/cave_01.obj", "res://levels/cave/mesh/cave_02.obj", "res://levels/cave/mesh/cave_10.obj", "res://levels/cave/mesh/cave_11.obj", "res://levels/cave/mesh/cave_12.obj", "res://levels/cave/mesh/cave_13.obj", "res://levels/cave/mesh/cave_20.obj", "res://levels/cave/mesh/cave_21.obj", "res://levels/cave/mesh/cave_22.obj", "res://levels/cave/mesh/cave_23.obj", "res://levels/cave/mesh/cave_30.obj", "res://levels/cave/mesh/cave_31.obj", "res://levels/cave/mesh/cave_32.obj"]
const SPAWN := Vector3(32.000, 0.000, 60.200)
## The daylight plane at the mouth, and where the rock seals it.
const MOUTH := Vector3(32.000, 0.000, 63.400)
const SEAL := Vector3(32.000, 0.000, 58.000)
## The door to the labyrinth: centre of the doorway on the floor; the face of the wall is at z.
const DOOR := Vector3(46.000, -4.000, 4.000)
const DOOR_SIZE := Vector2(1.70, 2.70)
const BONES := Vector3(9.000, -1.800, 26.000)
## Rooms: name -> [centre on the floor, radius].
const ROOMS := {
	"painted": [Vector3(29.000, -2.500, 14.000), 6.2],
	"bones": [Vector3(9.500, -1.800, 27.000), 3.5],
	"mouth": [Vector3(32.000, 0.000, 61.500), 3.2],
}
const PAINTINGS := [
	{"tex": "hands", "pos": Vector3(28.280, 1.332, 55.500), "normal": Vector3(1.000, -0.000, -0.000), "size": Vector2(1.70, 1.20),
		"line": "Hands. Dozens of them, blown in red around the fingers. Children's, some of them."},
	{"tex": "hunt", "pos": Vector3(29.770, 0.925, 47.600), "normal": Vector3(-1.000, -0.000, -0.000), "size": Vector2(2.40, 1.30),
		"line": "A hunt. Deer, and little men with spears. Someone lived here, once."},
	{"tex": "dragged", "pos": Vector3(5.830, -0.100, 27.200), "normal": Vector3(1.000, -0.000, -0.000), "size": Vector2(2.10, 1.50),
		"line": "People, and long arms reaching out of a circle. The arms are pulling them in."},
	{"tex": "monster", "pos": Vector3(28.800, -0.150, 7.830), "normal": Vector3(0.000, -0.000, 1.000), "size": Vector2(3.40, 2.40),
		"line": "It has no face. Just the eye, and the arms. They painted it bigger than anything else."},
	{"tex": "cave_map", "pos": Vector3(33.548, -0.750, 9.905), "normal": Vector3(-0.743, -0.000, 0.669), "size": Vector2(2.00, 1.80),
		"line": "A map. Of this cave — the bends, the rooms… and a door, at the end, with the sign over it."},
	{"tex": "land_map", "pos": Vector3(24.099, -0.800, 10.171), "normal": Vector3(0.788, -0.000, 0.616), "size": Vector2(2.10, 1.60),
		"line": "Rivers, and a ring of hills. That bend is where we made camp. I drew that bend yesterday."},
	{"tex": "procession", "pos": Vector3(43.000, -1.484, 15.330), "normal": Vector3(0.000, -0.000, 1.000), "size": Vector2(2.60, 1.20),
		"line": "A line of people walking into the ring. None of them are walking out."},
	{"tex": "spiral", "pos": Vector3(56.920, -1.949, 31.200), "normal": Vector3(-1.000, -0.000, -0.000), "size": Vector2(1.70, 1.60),
		"line": "Spirals, going in and in. I keep thinking they are moving."},
]
## A walking route from the mouth to the door (for tools/cave_test.gd).
const ROUTE := [
	Vector3(31.882, -0.017, 60.290),
	Vector3(31.567, -0.066, 58.883),
	Vector3(31.118, -0.130, 57.465),
	Vector3(30.500, -0.200, 56.000),
	Vector3(29.741, -0.260, 54.821),
	Vector3(28.752, -0.326, 53.617),
	Vector3(27.796, -0.396, 52.389),
	Vector3(27.136, -0.466, 51.136),
	Vector3(27.003, -0.534, 49.850),
	Vector3(27.315, -0.604, 48.500),
	Vector3(27.922, -0.674, 47.126),
	Vector3(28.695, -0.740, 45.776),
	Vector3(29.500, -0.800, 44.500),
	Vector3(30.447, -0.850, 43.391),
	Vector3(31.639, -0.896, 42.350),
	Vector3(32.807, -0.938, 41.336),
	Vector3(33.688, -0.975, 40.307),
	Vector3(34.019, -1.008, 39.189),
	Vector3(33.667, -1.037, 37.919),
	Vector3(32.851, -1.059, 36.618),
	Vector3(31.865, -1.079, 35.305),
	Vector3(31.000, -1.100, 34.000),
	Vector3(31.000, -1.100, 34.000),
	Vector3(32.104, -1.180, 33.000),
	Vector3(33.312, -1.260, 32.000),
	Vector3(34.468, -1.340, 31.000),
	Vector3(35.416, -1.420, 30.000),
	Vector3(36.000, -1.500, 29.000),
	Vector3(36.118, -1.614, 27.542),
	Vector3(35.659, -1.729, 26.073),
	Vector3(34.902, -1.843, 24.662),
	Vector3(34.120, -1.950, 23.452),
	Vector3(33.183, -2.050, 22.427),
	Vector3(32.110, -2.150, 21.456),
	Vector3(31.017, -2.250, 20.493),
	Vector3(29.500, -2.500, 16.500),
	Vector3(33.000, -2.600, 12.500),
	Vector3(34.333, -2.667, 13.065),
	Vector3(35.667, -2.733, 13.639),
	Vector3(37.000, -2.800, 14.204),
	Vector3(38.333, -2.867, 14.744),
	Vector3(39.675, -2.933, 15.280),
	Vector3(41.056, -2.996, 15.944),
	Vector3(42.436, -3.060, 16.584),
	Vector3(43.767, -3.127, 17.002),
	Vector3(45.000, -3.200, 17.000),
	Vector3(46.226, -3.284, 16.447),
	Vector3(47.460, -3.376, 15.473),
	Vector3(48.537, -3.470, 14.278),
	Vector3(49.294, -3.559, 13.058),
	Vector3(49.555, -3.647, 11.843),
	Vector3(49.144, -3.737, 10.440),
	Vector3(48.370, -3.819, 9.037),
	Vector3(47.632, -3.886, 7.776),
	Vector3(46.963, -3.948, 6.352),
	Vector3(46.324, -3.982, 5.128),
	Vector3(46.000, -4.000, 5.000),
]
