# Finale — "Waking": the labyrinth (three keys). Generated by tools/gen_level3.py.
#
# A grid of cells 3.5 m across. Characters sit on a (2N+1) x (2N+1) lattice:
#   corners   (even, even)  '+'  a stone pillar
#   edges     (odd/even)    '#'  wall     ' '  open     'D'  wooden door
#                           'I' 'T' 'K'  gates: iron, stone, black (need that key)
#                           'Q'  the silent room's door (it shuts behind you)
#                           'B'  a door barred on the wing side (opens only from there)
#                           'd'  a door that becomes a wall     'e'  a wall that becomes a door
#                           'X'  the Door of Light (outer wall)  'F'  a false door of light
#                           'h'  a wall that can sink            'j'  a gap a wall can rise into
#   cells     (odd, odd)    ' '  floor     'S'  where you wake     'M'  where the beast sleeps
#                           '1' '2' '3'  the Iron, Stone and Black keys
#                           'w'  will-o'-the-wisps   'p'  a torn page   'r'  rubble
extends RefCounted

const CELL := 3.5
const MAZE := [
	"+#+#+#+#+#+#+X+#+#+#+#+#+#+",
	"#2#     #w#  w  # #  w    #",
	"+ +#+#+ + + + + + + +#+#+ +",
	"#     # # #     #w# #  3  #",
	"+#+#+ + + +#+K+#+ + + + + +",
	"# #   # #         #     # #",
	"+ + +#+ +#+#+#+ + +D+ +#+ +",
	"# #w#   #p     r# # #   # #",
	"+ + +#+ + + +#+#+ + +D+#+ +",
	"# #   # # #  w    # # #  M#",
	"+ +#+ + + +#+#+#+ + + + +#+",
	"# # #   I #     # T # #   #",
	"+ + +#+ + + +#+ + + + +#+ +",
	"#    w  #w      #w# # #  w#",
	"+#+#+#+#+#+#+#+ + +#+B+#+#+",
	"# #   # # # # # # #       #",
	"+ + + +D+D+D+e+ + + +#+ + +",
	"F  w#           # #   #  w#",
	"+ +#+#+ +#+ +#+ + +#+ +#+ +",
	"#    p# #  w  #r#  w# #   F",
	"+#+#+j+ + +#+ + +#+ +#+ +#+",
	"#   Q h #    w        #   #",
	"+ + +j+ +#+#+#+#+#+#+ +d+ +",
	"#1  # #w  #      w  #    r#",
	"+#+#+ +#+ + +#+#+#+ + +#+ +",
	"#r           S      #w r p#",
	"+#+#+#+F+#+#+#+#+#+#+#+#+#+",
]
